### ISSUE TITLE
Encountered Violation of PRIMARY KEY constraint when calling UpdateAll

### ISSUE THREAD

**Issue by trgiangvp3** [RudeySH/EntityFramework.Utilities#18]
I load data from DB into `oldCamps` List, then do some modification and finally save it back to DB by using UpdateAll like below (`camRepo.BatchUpdate` is just a wrapper which calls `UpdateAll` under the hood)
```
campRepo.BatchUpdate(oldCamps, e => e.ColumnsToUpdate(
                        c => c.Name,
                        c => c.Description,
                        c => c.DeletedDate,
                        c => c.LastCheck,
                        c => c.Modified));    
```
```
public void BatchUpdate(IEnumerable<T> entities, Action<UpdateSpecification<T>> columnsToUpdate)
{
    if (entities != null && entities.Count() > 0)
        EFBatchOperation.For(_unitOfWork.Context, _unitOfWork.Context.Set<T>()).UpdateAll(entities, columnsToUpdate);
}
```

Sometimes I've got the following error
```
Violation of PRIMARY KEY constraint 'PK__temp_Cam__3214EC075C12819D'. Cannot insert duplicate key in object 'dbo.temp_Campaigns_636958659319135460'. The duplicate key value is (84896).
The statement has been terminated. ~    at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.TdsParser.Run(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj)
   at System.Data.SqlClient.SqlBulkCopy.RunParser(BulkCopySimpleResultSet bulkCopyHandler)
   at System.Data.SqlClient.SqlBulkCopy.CopyBatchesAsyncContinuedOnSuccess(BulkCopySimpleResultSet internalResults, String updateBulkCommandText, CancellationToken cts, TaskCompletionSource`1 source)
   at System.Data.SqlClient.SqlBulkCopy.CopyBatchesAsyncContinued(BulkCopySimpleResultSet internalResults, String updateBulkCommandText, CancellationToken cts, TaskCompletionSource`1 source)
   at System.Data.SqlClient.SqlBulkCopy.CopyBatchesAsync(BulkCopySimpleResultSet internalResults, String updateBulkCommandText, CancellationToken cts, TaskCompletionSource`1 source)
   at System.Data.SqlClient.SqlBulkCopy.WriteToServerInternalRestContinuedAsync(BulkCopySimpleResultSet internalResults, CancellationToken cts, TaskCompletionSource`1 source)
   at System.Data.SqlClient.SqlBulkCopy.WriteToServerInternalRestAsync(CancellationToken cts, TaskCompletionSource`1 source)
   at System.Data.SqlClient.SqlBulkCopy.WriteToServerInternalAsync(CancellationToken ctoken)
   at System.Data.SqlClient.SqlBulkCopy.WriteRowSourceToServerAsync(Int32 columnCount, CancellationToken ctoken)
   at System.Data.SqlClient.SqlBulkCopy.WriteToServer(IDataReader reader)
   at EntityFramework.Utilities.SqlQueryProvider.InsertItems[T](IEnumerable`1 items, String schema, String tableName, IList`1 properties, DbConnection storeConnection, Nullable`1 batchSize)
   at EntityFramework.Utilities.SqlQueryProvider.UpdateItems[T](IEnumerable`1 items, String schema, String tableName, IList`1 properties, DbConnection storeConnection, Nullable`1 batchSize, UpdateSpecification`1 updateSpecification)
   at EntityFramework.Utilities.EFBatchOperation`2.UpdateAll[TEntity](IEnumerable`1 items, Action`1 updateSpecification, DbConnection connection, Nullable`1 batchSize)
   at Campaigns.Repository.Repository`1.BatchUpdate(IEnumerable`1 entities, Action`1 columnsToUpdate)
```
I don't know exactly what `UpdateAll` method do, also I don't know what the table `dbo.temp_Campaigns_636958659319135460` 's PRIMARY KEY is. So, don't know where to start to debug.
Could you help me please.

**Comment by RudeySH** [comment]
I think you are using Mikael Eliasson's original [EFUtilities](https://www.nuget.org/packages/EFUtilities/), and not my fork [RudeySH.EFUtilities](https://www.nuget.org/packages/RudeySH.EFUtilities/). Either way, you would probably run into the same exception in my fork.

`UpdateAll` first inserts all entities into a temporary table, and runs an UPDATE query afterwards. The primary key of the temporary table will be the same as the table you're updating.

You're most likely running into "Violation of PRIMARY KEY constraint" because your `oldCamps` contains duplicates. You should probably figure out how to prevent that from happening, but you could also try using `oldCamps.Distinct()`.

**Comment by trgiangvp3** [comment]
Thank you for your response.
I think I knew where to start.
Will reply here when I found what the problem is.

**Comment by trgiangvp3** [comment]
I have finished my investigation.
The problem is exactly what you've said: `oldCamps` has duplicated elements.
The data source of `oldCamps` is from third party server which should not return duplicated data (but infact it does).
What I've done to by pass the error is distinct what I've got from the `oldCamps`' data source.
Thank you very much for your support.
